#OCU:
OCU_sub_Odometry: 'LOC'
OCU_sub_BladPosition: 'PER'
OCU_sub_Map: 'PER'
OCU_sub_WPDDecisions: 'WPD'
OCU_sub_LocalPath: 'PP'
OCU_sub_PlatformState: 'SSM'
OCU_sub_SoftwareState: 'SSM'
OCU_sub_SensorsState: 'SSM'
OCU_sub_SMMEMissionState: 'SMME'
OCU_sub_MissionAcceptance: 'SMME'

OCU_pub_PositionUpdate: '/OCU/PositionUpdate'
OCU_pub_SMMECommand: '/OCU/MissionExecutionCommands'
OCU_pub_SMMEControlMode: '/OCU/ControlMode'
OCU_pub_NavigationTask: '/OCU/NavigationTask'
OCU_pub_ManipulationTask: '/OCU/ManipulationTask'
OCU_pub_MissionTask: '/OCU/MissionPlan'
OCU_pub_CustomPath: '/OCU/Path'
OCU_pub_TeleoperationThrottle: '/OCU/Teleoperation/Throttle'
OCU_pub_TeleoperationSteering: '/OCU/Teleoperation/Steering'
OCU_pub_TeleoperationJoints: '/OCU/Teleoperation/Joints'
OCU_pub_IEDLocation: '/OCU/IED/Location'

#IEDSIM:
IEDSIM_sub_Odometry: 'LOC'
IEDSIM_sub_IEDLocation: 'OCU'
IEDSIM_sub_IEDSIMCommand: 'SMME'

IEDSIM_pub_IEDLocation: '/IED/Location'
IEDSIM_pub_IEDSIMComponentState: '/IED/ComponentState'

#SMME:
SMME_sub_Odometry: 'LOC'
SMME_sub_BladPosition: 'PER'
SMME_sub_PPExecutionState: 'PP'
SMME_sub_WSMExecutionState: 'WSM'
SMME_sub_IEDLocation: 'IEDSIM'
SMME_sub_PlatformState: 'SSM'
SMME_sub_SoftwareState: 'SSM'
SMME_sub_SensorsState: 'SSM'
SMME_sub_SMMECommand: 'OCU'
SMME_sub_SMMEControlMode: 'OCU'
SMME_sub_NavigationTask: 'OCU'
SMME_sub_ManipulationTask: 'OCU'
SMME_sub_MissionTask: 'OCU'

SMME_pub_WSMData: '/SMME/WSM/Data'
SMME_pub_MissionAcceptance: '/SMME/MissionAcceptance'
SMME_pub_GlobalPath: '/SMME/GlobalPath'
SMME_pub_MaxSpeed: '/SMME/MaxSpeed'
SMME_pub_SMMEMissionState: '/SMME/MissionState'
SMME_pub_SMMEComponentState: '/SMME/ComponentState'
SMME_pub_WPDCommand: '/SMME/WPD/Command'
SMME_pub_PPCommand: '/SMME/PP/Command'
SMME_pub_IEDSIMCommand: '/SMME/IEDSIM/Command'
SMME_pub_SSMCommand: '/SMME/SSM/Command'
SMME_pub_WSMCommand: '/SMME/WSM/Command'
SMME_pub_LLCCommand: '/SMME/LLC/Command'
SMME_pub_LOCCommand: '/SMME/LOC/Command'
SMME_pub_PERCommand: '/SMME/PER/Command'

#SSM:
SSM_sub_LLCPlatformState: 'LLC'
SSM_sub_Odometry: 'LOC'
SSM_sub_BladPosition: 'PER'
SSM_sub_PERSensorsState: 'PER'
SSM_sub_WPDDecisions: 'WPD'
SSM_sub_WSMExecutionState: 'WSM'
SSM_sub_SMMEMissionState: 'SMME'
SSM_sub_IEDSIMComponentState: 'IEDSIM'
SSM_sub_SMMEComponentState: 'SMME'
SSM_sub_SSMComponentState: 'SSM'
SSM_sub_LLCComponentState: 'LLC'
SSM_sub_LOCComponentState: 'LOC'
SSM_sub_PERComponentState: 'PER'
SSM_sub_PPComponentState: 'PP'
SSM_sub_WPDComponentState: 'WPD'
SSM_sub_SSMCommand: 'SMME'

SSM_pub_PlatformState: '/SSM/State/Platform'
SSM_pub_SoftwareState: '/SSM/State/Software'
SSM_pub_SensorsState: '/SSM/State/Sensors'
SSM_pub_SSMComponentState: '/SSM/ComponentState'

#WSM:
WSM_sub_Odometry: 'LOC'
WSM_sub_BladPosition: 'PER'
WSM_sub_WSMCommand: 'SMME'
WSM_sub_WSMData: 'SMME'

WSM_pub_BladePositionCommand: '/WSM/BladePosition'
WSM_pub_WSMSpeed: '/WSM/Speed'
WSM_pub_WSMExecutionState: '/WSM/ExecutionState'
WSM_pub_WSMComponentState: '/WSM/ComponentState'

#LLC:
LLC_sub_WSMSpeed: 'WSM'
LLC_sub_BladePositionCommand: 'WSM'
LLC_sub_WPDSpeed: 'WPD'
LLC_sub_Odometry: 'LOC'
LLC_sub_LLCCommand: 'SMME'
LLC_sub_TeleoperationThrottle: 'OCU'
LLC_sub_TeleoperationSteering: 'OCU'
LLC_sub_TeleoperationJoints: 'OCU'

LLC_pub_TrottleEffort: '/LLC/TrottleEffort'
LLC_pub_SteeringEffort: '/LLC/SteeringEffort'
LLC_pub_JointsEffort: '/LLC/JointsEffort'
LLC_pub_LLCPlatformState: '/LLC/PlatformState'
LLC_pub_LLCComponentState: '/LLC/ComponentState'

#LOC:
LOC_sub_VOOdometry: 'PER'
LOC_sub_GPS: 'PER'
LOC_sub_INS: 'PER'
LOC_sub_PositionUpdate: 'OCU'
LOC_sub_LOCCommand: 'SMME'

LOC_pub_Odometry: '/LOC/Odometry'
LOC_pub_LOCState: '/LOC/LOCState'
LOC_pub_LOCComponentState: '/LOC/ComponentState'

#PER:
PER_sub_Sensor_SICK_1: 'SENSORS' 
PER_sub_Sensor_SICK_2: 'SENSORS' 
PER_sub_Sensor_IBEO_1: 'SENSORS' 
PER_sub_Sensor_IBEO_2: 'SENSORS' 
PER_sub_Sensor_IBEO_3: 'SENSORS' 
PER_sub_Sensor_IBEO_4: 'SENSORS' 
PER_sub_Sensor_CAM_R: 'SENSORS'  
PER_sub_Sensor_CAM_L: 'SENSORS'  
PER_sub_Sensor_WIRE: 'SENSORS'   
PER_sub_Sensor_INS: 'SENSORS'    
PER_sub_Sensor_GPS: 'SENSORS'    
PER_sub_Odometry: 'LOC'          
PER_sub_TrottleEffort: 'LLC'     
PER_sub_SteeringEffort: 'LLC'    
PER_sub_JointsEffort: 'LLC'      
PER_sub_PERCommand: 'SMME'       

PER_pub_MiniMap: '/PER/MiniMap'
PER_pub_Map: '/PER/Map'
PER_pub_INS: '/PER/INS'
PER_pub_GPS: '/PER/GPS'
PER_pub_BladPosition: '/PER/PER_pub_BladPosition'
PER_pub_VOOdometry: '/PER/VO/Odometry'
PER_pub_SensorsCommand: '/PER/SensorsCommand'
PER_pub_PERSensorsState: '/PER/SensorsState'
PER_pub_PERComponentState: '/PER/ComponentState'

#SENSORS
SENSORS_pub_Sensor_SICK_1: '/SENSORS/SICK/1'
SENSORS_pub_Sensor_SICK_2: '/SENSORS/SICK/1'
SENSORS_pub_Sensor_IBEO_1: '/SENSORS/IBEO/1'
SENSORS_pub_Sensor_IBEO_2: '/SENSORS/IBEO/2'
SENSORS_pub_Sensor_IBEO_3: '/SENSORS/IBEO/3'
SENSORS_pub_Sensor_IBEO_4: '/SENSORS/IBEO/4'
SENSORS_pub_Sensor_CAM_R: '/SENSORS/CAM/R'
SENSORS_pub_Sensor_CAM_L: '/SENSORS/CAM/L'
SENSORS_pub_Sensor_WIRE: '/SENSORS/WIRE'
SENSORS_pub_Sensor_GPS: '/SENSORS/GPS'
SENSORS_pub_Sensor_INS: '/SENSORS/INS'

#PP
PP_sub_Map: 'PER'
PP_sub_Odometry: 'LOC'
PP_sub_PPCommand: 'SMME'
PP_sub_GlobalPath: 'SMME'
PP_sub_MaxSpeed: 'SMME'

PP_pub_LocalPath: '/PP/Path'
PP_pub_PPExecutionState: '/PP/ExecutionState'
PP_pub_PPComponentState: '/PP/ComponentState'

#WPD
WPD_sub_MiniMap: 'PER'
WPD_sub_LocalPath: 'PP' 
WPD_sub_MaxSpeed: 'SMME'
WPD_sub_Odometry: 'LOC' 
WPD_sub_WPDCommand: 'SMME'

WPD_pub_WPDSpeed: '/WPD/Speed'
WPD_pub_WPDDecisions: '/WPD/Decisions'
WPD_pub_WPDState: '/WPD/State'
WPD_pub_WPDComponentState: '/WPD/ComponentState'

