#IEDSIM
IEDSIM_sub_CustomIED: 'OCU'
IEDSIM_sub_LocalPath: 'PP'

IEDSIM_pub_IEDLocation: '/IED/Location'

#LLC
LLC_sub_WPD_Velocity: 'WPD'
LLC_sub_WSM_Velocity: 'WSM'
LLC_sub_BladePositionCommand: 'WSM'
LLC_sub_PerVelocity: 'LOC'
LLC_sub_Location: 'LOC'

LLC_pub_EffortsTh: '/LLC/EFFORTS/Throttle'
LLC_pub_EffortsSt: '/LLC/EFFORTS/Steering,Joints'
LLC_pub_EffortsJn: '/LLC/EFFORTS/Joints'

#OCU
OCU_sub_IEDLocation: 'IEDSIM'
OCU_sub_MissionAcceptance: 'SMME'
OCU_sub_LocalPath: 'PP'
OCU_sub_Blade: 'PER'
OCU_sub_Map: 'PER'
OCU_sub_PerVelocity: 'LOC'
OCU_sub_Location: 'LOC'

OCU_pub_CustomIED: '/OCU/IED/Location'
OCU_pub_PositionUpdate: '/OCU/PositionUpdate'
OCU_pub_AssignNavTask: '/OCU/SMME/NavigationTask'
OCU_pub_AssignManTask: '/OCU/SMME/ManipulationTask'
OCU_pub_AssignMission: '/OCU/SMME/MissionPlan'

#PER
PER_sub_PerVelocity: 'LOC'
PER_sub_Location: 'LOC'
PER_sub_SenINS: 'SENSORS'
PER_sub_SenGPS: 'SENSORS'
PER_sub_SenCamL: 'SENSORS'
PER_sub_SenCamR: 'SENSORS'
PER_sub_SenWire: 'SENSORS'
PER_sub_SenSICK: 'SENSORS'
PER_sub_SenIBEO1: 'SENSORS'
PER_sub_SenIBEO2: 'SENSORS'
PER_sub_SenIBEO3: 'SENSORS'
PER_sub_SenIBEO4: 'SENSORS'
PER_sub_EffortsTh: 'LLC'
PER_sub_EffortsSt: 'LLC'
PER_sub_EffortsJn: 'LLC'

PER_pub_GPS: '/PER/GPS'
PER_pub_INS: '/PER/INS'
PER_pub_Blade: '/PER/BladPosition'
PER_pub_Map: '/PER/Map'
PER_pub_MiniMap: '/PER/MiniMap'
PER_pub_VO: '/PER/VO'

#PP
PP_sub_GlobalPath: 'SMME'
PP_sub_Blade: 'PER'
PP_sub_Map: 'PER'
PP_sub_MiniMap: 'PER'

PP_pub_LocalPath: '/PP/Path'

#SMME
SMME_sub_IEDLocation: 'IEDSIM'
SMME_sub_AssignNavTask: 'OCU'
SMME_sub_AssignManTask: 'OCU'
SMME_sub_AssignMission: 'OCU'
SMME_sub_Blade: 'PER'
SMME_sub_PerVelocity: 'LOC'
SMME_sub_Location: 'LOC'

SMME_pub_GlobalPath: '/SMME/GlobalPath'
SMME_pub_WorkSeqData: '/SMME/WSM/Task'
SMME_pub_MissionAcceptance: '/SMME/OCU/MissionAcceptance'

#SSM
SSM_sub_Blade: 'PER'
SSM_sub_PerVelocity: 'LOC'
SSM_sub_Location: 'LOC'


#WPD
WPD_sub_LocalPath: 'PP'
WPD_sub_PerVelocity: 'LOC'
WPD_sub_Location: 'LOC'

WPD_pub_WPD_Velocity: '/WPD/Speed'

#WSM
WSM_sub_WorkSeqData: 'SMME'
WSM_sub_Blade: 'PER'
WSM_sub_PerVelocity: 'LOC'
WSM_sub_Location: 'LOC'

WSM_pub_WSM_Velocity: '/WSM/Speed'
WSM_pub_BladePositionCommand: '/WSM/BladePosition'

#LOC
LOC_sub_PositionUpdate: 'OCU'
LOC_sub_GPS: 'PER'
LOC_sub_INS: 'PER'
LOC_sub_VO: 'PER'

LOC_pub_PerVelocity: '/LOC/Velocity'
LOC_pub_Location: '/LOC/Pose'

#SENSORS

SENSORS_pub_SenINS: '/SENSORS/IMU'
SENSORS_pub_SenGPS: '/SENSORS/GPS'
SENSORS_pub_SenCamL: '/SENSORS/CAM/L'
SENSORS_pub_SenCamR: '/SENSORS/CAM/R'
SENSORS_pub_SenWire: '/SENSORS/WIRE'
SENSORS_pub_SenSICK: '/SENSORS/SICK/1'
SENSORS_pub_SenIBEO1: '/SENSORS/IBEO/1'
SENSORS_pub_SenIBEO2: '/SENSORS/IBEO/2'
SENSORS_pub_SenIBEO3: '/SENSORS/IBEO/3'
SENSORS_pub_SenIBEO4: '/SENSORS/IBEO/4'

#PLATFORM
PLATFORM_sub_EffortsTh: 'LLC'
PLATFORM_sub_EffortsSt: 'LLC'
PLATFORM_sub_EffortsJn: 'LLC'

